### ISSUE TITLE
Cant start skyhook

### ISSUE THREAD

**Issue by DiseaseNO** [CmdrShepard/Skyhook#1]
Hi. I cant get skyhook to start. This is the log:

> *** Starting uWSGI 2.0.14 (64bit) on [Tue Dec  6 09:35:03 2016] ***
compiled with version: 4.9.2 on 06 December 2016 09:13:14
os: Linux-3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02)
nodename: xxxxxxx
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/skyhook/src
detected binary path: /opt/skyhook/venv2/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
your processes number limit is 15310
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/skyhook.sock fd 8
Python version: 3.5.2 (default, Dec  6 2016, 00:55:03)  [GCC 4.9.2]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1615300
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145536 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./wsgi.py", line 2, in <module>
    from skyhook import app
  File "./skyhook/__init__.py", line 3, in <module>
    from instance.config import DebugConfig
ImportError: cannot import name 'DebugConfig'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4453)
spawned uWSGI worker 1 (pid: 4455, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 0 seconds
goodbye to uWSGI.
VACUUM: unix socket /tmp/skyhook.sock removed.

**Comment by CmdrShepard** [comment]
I forgot to add the config file, I've done this in 800a3686508d9c71cea32d93544dfdcecbe1e999.

Try again and it should work!
