### ISSUE TITLE
Error: could not determine PostgreSQL version from '11.7' (Debian 10)

### ISSUE THREAD

**Issue by solbu** [CmdrShepard/Skyhook#4]
Hi.
We are trying to install this on Debian 10 and have problems.
It halts with the error in title:

These are the commands we used to install dependencies, in case it matters.
(We prefer packaged versions over pip-versions)
<pre>apt install postgresql postgresql-contrib python3.7 python3.7-dev python3-pip libpq-dev libxml2-dev libxslt1-dev
apt install virtualenv
apt install uwsgi
source venv/bin/activate
pip3 install -e .                                                                                                                                                                                        
Obtaining file:///opt/skyhook
Collecting Flask==0.10.1
  Using cached Flask-0.10.1.tar.gz (544 kB)
Collecting Flask-SQLAlchemy==2.1
  Using cached Flask-SQLAlchemy-2.1.tar.gz (95 kB)
Collecting lxml==3.6.0
  Using cached lxml-3.6.0.tar.gz (3.7 MB)
Collecting psycopg2==2.6.1
  Using cached psycopg2-2.6.1.tar.gz (371 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/skyhook/venv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-90_h7q_p/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-90_h7q_p/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-sfme3224                                              
         cwd: /tmp/pip-install-90_h7q_p/psycopg2/
    Complete output (7 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-sfme3224/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-sfme3224/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-sfme3224/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-sfme3224/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-sfme3224/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '11.7'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.</pre>

**Comment by CmdrShepard** [comment]
Upgrade the psycopg2 version, you would need at least 2.7 for PostgreSQL 11.7, but I would go for the newest one (2.8.5), see https://pypi.org/project/psycopg2/

https://github.com/CmdrShepard/Skyhook/blob/master/setup.py#L35

Change:
`'psycopg2==2.6.1',`
to:
`'psycopg2==2.8.5',`

Ideally this should be packaged in a Docker build to prevent this in the future.
