### ISSUE TITLE
Skyhook not serving the right episodes for DuckTales (2017)

### ISSUE THREAD

**Issue by PoloDePoli** [CmdrShepard/Skyhook#7]
The issue is described in [https://www.reddit.com/r/sonarr/comments/k2p185/phantom_ducktales_2017_episode_in_sonarr_only/](https://www.reddit.com/r/sonarr/comments/k2p185/phantom_ducktales_2017_episode_in_sonarr_only/)

Essentially for DuckTales (2017) season 3 Sonarr displays E12 (as per TVDB & TMDB) as split into Part 1 (E12) and Part 2 (E13).
This then offsets all the following episodes (e.g. E13 becomes E14, etc) creating issues with managing the series.

RhynoRys pointed out that this is not an issue with waiting for 24h for Skyhook to match TVDB as (quoting his [post](https://www.reddit.com/r/sonarr/comments/k2p185/phantom_ducktales_2017_episode_in_sonarr_only/gdx8iwv?utm_source=share&utm_medium=web2x&context=3))
> TheTVDB has this tagged as last edited on October 5th so waiting wont help, I've also checked with my own API key and its not showing in the data. Sonarr actually downloads from skyhook which is their own personal cache of the TVDB to reduce the API traffic. This episode is on there. Its also on the "intended viewing order" of season 3 on theTVDB rather than the "aired order" you were looking at.
> Heres the skyhook link if you care to read through the JSON code.
> http://skyhook.sonarr.tv/v1/tvdb/shows/en/330134

Thank you for your help

**Comment by PoloDePoli** [comment]
Apparently it might still be an issue with the 24h - another user of reddit stated they have seen the different variations this week despite the "last edited tag" of October 5th

**Comment by CmdrShepard** [comment]
This repository is not for the official Skyhook service, but rather a custom service to replace Skyhook locally. You need to raise an issue at the correct repo: https://github.com/Sonarr/Sonarr
